### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/generator-swiftserver-projects#21]
Projects generated by the Kitura CLI should now use Swift 4.2 by default.

**Comment by DunnCoding** [comment]
This issue will be resolved under this [PR](https://github.com/IBM-Swift/generator-swiftserver-projects/pull/23)

This will mean both the `init` and `openAPI` branches will be updated periodically from the [generator-swiftserver](https://github.com/IBM-Swift/generator-swiftserver) and as such will include Swift 4.2 by default.
